name: franklab
on:
  workflow_dispatch:
  schedule:
    - cron: "37 9 * * *" # 9:37 AM UTC every day
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          cd devel/prepare_session_files
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Upgrade position-tools
        run: |
          pip install --upgrade position-tools
      - name: create table names
        run: |
          python devel/prepare_session_files/create_table_names.py
        env:
          DJ_DATABASE_HOST_FRANKLAB: ${{ secrets.DJ_DATABASE_HOST_FRANKLAB }}
          DJ_DATABASE_USER_FRANKLAB: ${{ secrets.DJ_DATABASE_USER_FRANKLAB }}
          DJ_DATABASE_PASSWORD_FRANKLAB: ${{ secrets.DJ_DATABASE_PASSWORD_FRANKLAB }}
      - name: prepare session files
        run: |
          python devel/prepare_session_files/prepare_session_files.py
        env:
          DJ_DATABASE_HOST_FRANKLAB: ${{ secrets.DJ_DATABASE_HOST_FRANKLAB }}
          DJ_DATABASE_USER_FRANKLAB: ${{ secrets.DJ_DATABASE_USER_FRANKLAB }}
          DJ_DATABASE_PASSWORD_FRANKLAB: ${{ secrets.DJ_DATABASE_PASSWORD_FRANKLAB }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT_URL }}
